#
# Bitte gegebenenfalls anpassen:
#
NETWORK_PREFIX = "192.168.150"

$install_ansible_debian = <<-SCRIPT
sudo apt update
sudo apt install -y ansible
SCRIPT

$install_ansible_centos = <<-SCRIPT
sudo yum install -y epel-release
sudo yum install -y ansible
#
SCRIPT

$install_ansible_suse = <<-SCRIPT
sudo zypper install -y ansible
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "bento/debian-11"
    ansible.vm.hostname = "ansible"
    ansible.vm.network :private_network, ip: "#{NETWORK_PREFIX}.100"
    ansible.vm.provision "shell", name: "install_ansible_debian", inline: $install_ansible_debian
  end

  config.vm.define "debian" do |debian|
    debian.vm.box = "bento/debian-11"
    debian.vm.hostname = "debian"
    debian.vm.network :private_network, ip: "#{NETWORK_PREFIX}.10"
    debian.vm.provision "shell", name: "install_ansible_debian", inline: $install_ansible_debian
  end

  config.vm.define "rocky" do |rocky|
    rocky.vm.box = "bento/rockylinux-8"
    rocky.vm.hostname = "rocky"
    rocky.vm.network :private_network, ip: "#{NETWORK_PREFIX}.20"
    rocky.vm.provision "shell", name: "install_ansible_centos", inline: $install_ansible_centos
  end

  config.vm.define "suse" do |suse|
    suse.vm.box = "bento/opensuse-leap-15"
    suse.vm.hostname = "suse"
    suse.vm.network :private_network, ip: "#{NETWORK_PREFIX}.30"
    suse.vm.provision "shell", name: "install_ansible_suse", inline: $install_ansible_suse
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-20.04"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network :private_network, ip: "#{NETWORK_PREFIX}.40"
    ubuntu.vm.provision "shell", name: "install_ansible_debian", inline: $install_ansible_debian
  end

end
